Support for liveness probe for ovs-cni marker
k8snetworkplumbingwg/ovs-cni pull request #231
Opened 2022-06-14 11:00 UTC by rthakur-est

This change adds support for file based liveness probe for ovs-cni marker.
This is done by changing the modification time of "/tmp/healthy" file
from the marker code. And the exec probe verifies that the file has been
modified in last one minute.

#230 

Signed-off-by: Ravindra Thakur <ravindra.nath.thakur@est.tech>

2022-06-14 12:06 UTC, phoracek requested changes
Looks and works well, thanks for the contribution. I left some small comments.

2022-06-14 12:06 UTC, phoracek commented on cmd/marker/main.go
> +func keepAlive() {
Would you please introduce a new test into https://github.com/k8snetworkplumbingwg/ovs-cni/blob/main/tests/marker_test.go verifying that the pod survives the health check and does not get restarted?

2022-06-14 12:06 UTC, phoracek commented
/retest

2022-06-15 05:11 UTC, rthakur-est commented on manifests/ovs-cni.yml.in
> +          periodSeconds: 15
I completely agree with this. I will change the timer intervals to 1 minute.

2022-06-17 09:59 UTC, rthakur-est commented
/retest

2022-06-17 11:39 UTC, phoracek commented
/retest

2022-06-17 14:04 UTC, phoracek approved these changes
/lgtm
/approve

Fantastic, thanks a lot @rthakur-est ! I failed the check offline and it restarted the pod as expected.

2022-06-17 14:26 UTC, phoracek commented
/release-note-none

2022-06-17 14:26 UTC, phoracek commented
/retest

Failed on timeout. I will post a patch increasing the 10 minute test timeout

2022-06-17 14:49 UTC, phoracek commented
/retest

2022-06-17 15:16 UTC, phoracek commented
/retest

2022-06-17 15:17 UTC, phoracek commented
/test pull-e2e-ovs-cni

2022-06-17 15:19 UTC, phoracek commented
/retest

2022-06-17 16:51 UTC, merged

2022-06-20 05:15 UTC, rthakur-est commented
@phoracek Thanks for the quick review.