Provides a possible way to set interface's type of one port
k8snetworkplumbingwg/ovs-cni pull request #252
Opened 2022-11-10 08:28 UTC by wangyueyu64

In the current code, only the 'internal' type which is also the defaut type of interface is available when ovs-cni create one interface for port.
I added extra content to provides a possible way of setting interface's type when cni call func 'attachIfaceToBridge’.
In order to accommodate this function, also expanded type NetConf for ovs-cni and added extra arguments to function ‘attachIfaceToBridge'.
This will allow the user to select a custom type of interface when creating a port on bridge.

Signed-off-by: wangyueyu <wangyueyu@didiglobal.com>

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2022-11-10 09:24 UTC, phoracek requested changes
The code looks fine. Would you please add test cases to https://github.com/k8snetworkplumbingwg/ovs-cni/blob/main/pkg/plugin/plugin_test.go covering the default type (without interface_type passed) and one for a custom type?

2022-11-10 10:16 UTC, wangyueyu64 commented
> The code looks fine. Would you please add test cases to https://github.com/k8snetworkplumbingwg/ovs-cni/blob/main/pkg/plugin/plugin_test.go covering the default type (without interface_type passed) and one for a custom type?

Thank you for your reply. I will supplement the test content as soon as possible.

2022-11-16 10:31 UTC, wangyueyu64 commented
> The code looks fine. Would you please add test cases to https://github.com/k8snetworkplumbingwg/ovs-cni/blob/main/pkg/plugin/plugin_test.go covering the default type (without interface_type passed) and one for a custom type?

Add new test content for interface type.

2022-11-24 11:17 UTC, phoracek commented
/test pull-e2e-ovs-cni

2022-11-25 14:31 UTC, phoracek commented
The test fails on the CI, probably due to afxdp support not being present in a default installation of OVS. I tried it locally and it also failed. Reading https://docs.openvswitch.org/en/latest/intro/install/afxdp/, it mentions that this specific type is experimental and compiled by default.

Could we change the type used in tests to one that is generally supported? To make sure that these tests can be executed on regular environments of other developers. `local` type may be a good choice.

2022-12-12 12:20 UTC, phoracek commented
@wangyueyu64 hello, this has been silent for a while. Can I help with anything regarding the tests?

2022-12-16 04:18 UTC, wangyueyu64 commented
I am very sorry that I have replied to your message only now due to work reasons. I will use more&nbsp;general&nbsp;interface types as test cases, such as tap or system. I will submit it again after the modification is completed.



---Original---
From: "Petr ***@***.***&gt;
Date: Mon, Dec 12, 2022 20:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [k8snetworkplumbingwg/ovs-cni] Provides a possible way to setinterface's type of one port (PR #252)




 
@wangyueyu64 hello, this has been silent for a while. Can I help with anything regarding the tests?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-12-16 11:21 UTC, phoracek commented
That's all good, don't worry about that :)

2022-12-26 03:09 UTC, wangyueyu64 commented
> That's all good, don't worry about that :)

2022-12-26 03:11 UTC, wangyueyu64 commented
The afxdp type interface content in the test file has been replaced with the  interface of type system type.

2023-01-02 13:06 UTC, phoracek commented
/retest

2023-01-03 17:15 UTC, phoracek commented
/release-note-none

2023-01-03 17:16 UTC, merged